shell = "zsh"

[plugins.omz]
github = "ohmyzsh/ohmyzsh"
use = [
  "lib/directories.zsh",
  "lib/theme-and-appearance.zsh",
  "lib/async_prompt.zsh",
  "lib/git.zsh",
  "plugins/extract/extract.plugin.zsh",
  "plugins/history/history.plugin.zsh",
  "plugins/sudo/sudo.plugin.zsh",
]

[plugins.history-substring-search]
github = "zsh-users/zsh-history-substring-search"

[plugins.autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.syntax-highlighting]
github = "zsh-users/zsh-syntax-highlighting"

[plugins.sslees-theme]
local = "~/dotfiles"
use = ["sslees.zsh-theme"]
